from __future__ import annotations

from ..Proxy import proxy_property, AccessMode
from ..AcadObject import AcadObject


class AcadSectionTypeSettings(AcadObject):
    def __init__(self, obj) -> None:
        super().__init__(obj)

    BackgroundLinesColor: AcadAcCmColor = proxy_property('AcadAcCmColor', 'BackgroundLinesColor', AccessMode.ReadWrite)
    BackgroundLinesLayer: str = proxy_property(str, 'BackgroundLinesLayer', AccessMode.ReadWrite)
    BackgroundLinesLinetype: str = proxy_property(str, 'BackgroundLinesLinetype', AccessMode.ReadWrite)
    BackgroundLinesLinetypeScale: float = proxy_property(float, 'BackgroundLinesLinetypeScale', AccessMode.ReadWrite)
    BackgroundLinesLineweight: AcLineWeight = proxy_property('AcLineWeight', 'BackgroundLinesLineweight', AccessMode.ReadWrite)
    BackgroundLinesVisible: bool = proxy_property(bool, 'BackgroundLinesVisible', AccessMode.ReadWrite)
    CurveGenerationSettings: int = proxy_property(int, 'CurveGenerationSettings', AccessMode.ReadWrite)
    DestinationBlock: str = proxy_property(str, 'DestinationBlock', AccessMode.ReadWrite)
    DestinationFile: str = proxy_property(str, 'DestinationFile', AccessMode.ReadWrite)
    ForegroundLinesColor: AcadAcCmColor = proxy_property('AcadAcCmColor', 'ForegroundLinesColor', AccessMode.ReadWrite)
    ForegroundLinesLayer: str = proxy_property(str, 'ForegroundLinesLayer', AccessMode.ReadWrite)
    ForegroundLinesLinetype: str = proxy_property(str, 'ForegroundLinesLinetype', AccessMode.ReadWrite)
    ForegroundLinesLinetypeScale: float = proxy_property(float, 'ForegroundLinesLinetypeScale', AccessMode.ReadWrite)
    ForegroundLinesLineweight: AcLineWeight = proxy_property('AcLineWeight', 'ForegroundLinesLineweight', AccessMode.ReadWrite)
    ForegroundLinesVisible: bool = proxy_property(bool, 'ForegroundLinesVisible', AccessMode.ReadWrite)
    GenerationOptions: int = proxy_property(int, 'GenerationOptions', AccessMode.ReadWrite)
    IntersectionBoundaryColor: AcadAcCmColor = proxy_property('AcadAcCmColor', 'IntersectionBoundaryColor', AccessMode.ReadWrite)
    IntersectionBoundaryDivisionLines: bool = proxy_property(bool, 'IntersectionBoundaryDivisionLines', AccessMode.ReadWrite)
    IntersectionBoundaryLayer: str = proxy_property(str, 'IntersectionBoundaryLayer', AccessMode.ReadWrite)
    IntersectionBoundaryLinetype: str = proxy_property(str, 'IntersectionBoundaryLinetype', AccessMode.ReadWrite)
    IntersectionBoundaryLinetypeScale: float = proxy_property(float, 'IntersectionBoundaryLinetypeScale', AccessMode.ReadWrite)
    IntersectionBoundaryLineweight: AcLineWeight = proxy_property('AcLineWeight', 'IntersectionBoundaryLineweight', AccessMode.ReadWrite)
    IntersectionBoundaryVisible: bool = proxy_property(bool, 'IntersectionBoundaryVisible', AccessMode.ReadWrite)
    IntersectionFillColor: AcadAcCmColor = proxy_property('AcadAcCmColor', 'IntersectionFillColor', AccessMode.ReadWrite)
    IntersectionFillFaceTransparency: int = proxy_property(int, 'IntersectionFillFaceTransparency', AccessMode.ReadWrite)
    IntersectionFillHatchAngle: float = proxy_property(float, 'IntersectionFillHatchAngle', AccessMode.ReadWrite)
    IntersectionFillHatchPatternName: str = proxy_property(str, 'IntersectionFillHatchPatternName', AccessMode.ReadWrite)
    IntersectionFillHatchPatternType: AcPatternType = proxy_property('AcPatternType', 'IntersectionFillHatchPatternType', AccessMode.ReadWrite)
    IntersectionFillHatchScale: float = proxy_property(float, 'IntersectionFillHatchScale', AccessMode.ReadWrite)
    IntersectionFillHatchSpacing: float = proxy_property(float, 'IntersectionFillHatchSpacing', AccessMode.ReadWrite)
    IntersectionFillLayer: str = proxy_property(str, 'IntersectionFillLayer', AccessMode.ReadWrite)
    IntersectionFillLinetype: str = proxy_property(str, 'IntersectionFillLinetype', AccessMode.ReadWrite)
    IntersectionFillLinetypeScale: float = proxy_property(float, 'IntersectionFillLinetypeScale', AccessMode.ReadWrite)
    IntersectionFillLineweight: AcLineWeight = proxy_property('AcLineWeight', 'IntersectionFillLineweight', AccessMode.ReadWrite)
    IntersectionFillVisible: bool = proxy_property(bool, 'IntersectionFillVisible', AccessMode.ReadWrite)
    SourceObjects: str = proxy_property(str, 'SourceObjects', AccessMode.ReadWrite)
    IntersectionBoundaryColor2: AcadAcCmColor = proxy_property('AcadAcCmColor', 'IntersectionBoundaryColor2', AccessMode.ReadWrite)
    IntersectionBoundaryLayer2: str = proxy_property(str, 'IntersectionBoundaryLayer2', AccessMode.ReadWrite)
    IntersectionBoundaryLinetype2: str = proxy_property(str, 'IntersectionBoundaryLinetype2', AccessMode.ReadWrite)
    IntersectionBoundaryLinetypeScale2: float = proxy_property(float, 'IntersectionBoundaryLinetypeScale2', AccessMode.ReadWrite)
    IntersectionBoundaryLineweight2: AcLineWeight = proxy_property('AcLineWeight', 'IntersectionBoundaryLineweight2', AccessMode.ReadWrite)
    IntersectionBoundaryVisible2: bool = proxy_property(bool, 'IntersectionBoundaryVisible2', AccessMode.ReadWrite)
    IntersectionFillColor2: AcadAcCmColor = proxy_property('AcadAcCmColor', 'IntersectionFillColor2', AccessMode.ReadWrite)
    IntersectionFillFaceTransparency2: int = proxy_property(int, 'IntersectionFillFaceTransparency2', AccessMode.ReadWrite)
    IntersectionFillHatchAngle2: float = proxy_property(float, 'IntersectionFillHatchAngle2', AccessMode.ReadWrite)
    IntersectionFillHatchPatternName2: str = proxy_property(str, 'IntersectionFillHatchPatternName2', AccessMode.ReadWrite)
    IntersectionFillHatchPatternType2: AcPatternType = proxy_property('AcPatternType', 'IntersectionFillHatchPatternType2', AccessMode.ReadWrite)
    IntersectionFillHatchScale2: float = proxy_property(float, 'IntersectionFillHatchScale2', AccessMode.ReadWrite)
    IntersectionFillHatchSpacing2: float = proxy_property(float, 'IntersectionFillHatchSpacing2', AccessMode.ReadWrite)
    IntersectionFillLayer2: str = proxy_property(str, 'IntersectionFillLayer2', AccessMode.ReadWrite)
    IntersectionFillLinetype2: str = proxy_property(str, 'IntersectionFillLinetype2', AccessMode.ReadWrite)
    IntersectionFillLinetypeScale2: float = proxy_property(float, 'IntersectionFillLinetypeScale2', AccessMode.ReadWrite)
    IntersectionFillLineweight2: AcLineWeight = proxy_property('AcLineWeight', 'IntersectionFillLineweight2', AccessMode.ReadWrite)
    IntersectionFillVisible2: bool = proxy_property(bool, 'IntersectionFillVisible2', AccessMode.ReadWrite)
