from __future__ import annotations

from ..Base import AppObject
from ..Proxy import proxy_property, AccessMode


class AcadSectionTypeSettings(AppObject):
    def __init__(self, obj) -> None:
        super().__init__(obj)

    BackgroundLinesColor = proxy_property('AcadAcCmColor', 'BackgroundLinesColor', AccessMode.ReadWrite)
    BackgroundLinesHiddenLine = proxy_property(bool, 'BackgroundLinesHiddenLine', AccessMode.ReadWrite)
    BackgroundLinesLayer = proxy_property(str, 'BackgroundLinesLayer', AccessMode.ReadWrite)
    BackgroundLinesLinetypeScale = proxy_property(float, 'BackgroundLinesLinetypeScale', AccessMode.ReadWrite)
    BackgroundLinesLineweight = proxy_property('AcLineWeight', 'BackgroundLinesLineweight', AccessMode.ReadWrite)
    BackgroundLinesPlotStyleName = proxy_property(str, 'BackgroundLinesPlotStyleName', AccessMode.ReadWrite)
    BackgroundLinesVisible = proxy_property(bool, 'BackgroundLinesVisible', AccessMode.ReadWrite)
    CurveTangencyLinesColor = proxy_property('AcadAcCmColor', 'CurveTangencyLinesColor', AccessMode.ReadWrite)
    CurveTangencyLinesLayer = proxy_property(str, 'CurveTangencyLinesLayer', AccessMode.ReadWrite)
    CurveTangencyLinesLinetype = proxy_property(str, 'CurveTangencyLinesLinetype', AccessMode.ReadWrite)
    CurveTangencyLinesLinetypeScale = proxy_property(float, 'CurveTangencyLinesLinetypeScale', AccessMode.ReadWrite)
    CurveTangencyLinesLineweight = proxy_property('AcLineWeight', 'CurveTangencyLinesLineweight', AccessMode.ReadWrite)
    CurveTangencyLinesPlotStyleName = proxy_property(str, 'CurveTangencyLinesPlotStyleName', AccessMode.ReadWrite)
    CurveTangencyLinesVisible = proxy_property(bool, 'CurveTangencyLinesVisible', AccessMode.ReadWrite)
    DestinationBlock = proxy_property('Variant', 'DestinationBlock', AccessMode.ReadWrite)
    DestinationFile = proxy_property(str, 'DestinationFile', AccessMode.ReadWrite)
    ForegroundLinesColor = proxy_property('AcadAcCmColor', 'ForegroundLinesColor', AccessMode.ReadWrite)
    ForegroundLinesEdgeTransparency = proxy_property(int, 'ForegroundLinesEdgeTransparency', AccessMode.ReadWrite)
    ForegroundLinesFaceTransparency = proxy_property(int, 'ForegroundLinesFaceTransparency', AccessMode.ReadWrite)
    ForegroundLinesHiddenLine = proxy_property(bool, 'ForegroundLinesHiddenLine', AccessMode.ReadWrite)
    ForegroundLinesLayer = proxy_property(str, 'ForegroundLinesLayer', AccessMode.ReadWrite)
    ForegroundLinesLinetype = proxy_property(str, 'ForegroundLinesLinetype', AccessMode.ReadWrite)
    ForegroundLinesLinetypeScale = proxy_property(float, 'ForegroundLinesLinetypeScale', AccessMode.ReadWrite)
    ForegroundLinesLineweight = proxy_property('AcLineWeight', 'ForegroundLinesLineweight', AccessMode.ReadWrite)
    ForegroundLinesPlotStyleName = proxy_property(str, 'ForegroundLinesPlotStyleName', AccessMode.ReadWrite)
    ForegroundLinesVisible = proxy_property(bool, 'ForegroundLinesVisible', AccessMode.ReadWrite)
    GenerationOptions = proxy_property('AcSectionGeneration', 'GenerationOptions', AccessMode.ReadWrite)
    IntersectionBoundaryColor = proxy_property('AcadAcCmColor', 'IntersectionBoundaryColor', AccessMode.ReadWrite)
    IntersectionBoundaryDivisionLines = proxy_property(bool, 'IntersectionBoundaryDivisionLines', AccessMode.ReadWrite)
    IntersectionBoundaryLayer = proxy_property(str, 'IntersectionBoundaryLayer', AccessMode.ReadWrite)
    IntersectionBoundaryLinetype = proxy_property(str, 'IntersectionBoundaryLinetype', AccessMode.ReadWrite)
    IntersectionBoundaryLinetypeScale = proxy_property(float, 'IntersectionBoundaryLinetypeScale', AccessMode.ReadWrite)
    IntersectionBoundaryLineweight = proxy_property('AcLineWeight', 'IntersectionBoundaryLineweight', AccessMode.ReadWrite)
    IntersectionBoundaryPlotStyleName = proxy_property(str, 'IntersectionBoundaryPlotStyleName', AccessMode.ReadWrite)
    IntersectionBoundaryVisible = proxy_property(bool, 'IntersectionBoundaryVisible', AccessMode.ReadWrite)
    IntersectionFillColor = proxy_property('AcadAcCmColor', 'IntersectionFillColor', AccessMode.ReadWrite)
    IntersectionFillFaceTransparency = proxy_property(int, 'IntersectionFillFaceTransparency', AccessMode.ReadWrite)
    IntersectionFillHatchAngle = proxy_property(float, 'IntersectionFillHatchAngle', AccessMode.ReadWrite)
    IntersectionFillHatchPatternName = proxy_property(str, 'IntersectionFillHatchPatternName', AccessMode.ReadWrite)
    IntersectionFillHatchPatternType = proxy_property('AcPatternType', 'IntersectionFillHatchPatternType', AccessMode.ReadWrite)
    IntersectionFillHatchScale = proxy_property(float, 'IntersectionFillHatchScale', AccessMode.ReadWrite)
    IntersectionFillHatchSpacing = proxy_property(float, 'IntersectionFillHatchSpacing', AccessMode.ReadWrite)
    IntersectionFillLayer = proxy_property(str, 'IntersectionFillLayer', AccessMode.ReadWrite)
    IntersectionFillLinetype = proxy_property(str, 'IntersectionFillLinetype', AccessMode.ReadWrite)
    IntersectionFillLinetypeScale = proxy_property(float, 'IntersectionFillLinetypeScale', AccessMode.ReadWrite)
    IntersectionFillLineweight = proxy_property('AcLineWeight', 'IntersectionFillLineweight', AccessMode.ReadWrite)
    IntersectionFillPlotStyleName = proxy_property(str, 'IntersectionFillPlotStyleName', AccessMode.ReadWrite)
    IntersectionFillVisible = proxy_property(bool, 'IntersectionFillVisible', AccessMode.ReadWrite)
    SourceObjects = proxy_property('Variant', 'SourceObjects', AccessMode.ReadWrite)
